### ISSUE TITLE
Training Code

### ISSUE THREAD

**Issue by Houwj17** [Pter61/context-i2w#9]
It's wonderful  work. When will the “trainer.py” file be provided?

**Comment by Pter61** [comment]
Thank you for your interest in our work! We will be providing the 'trainer.py' file and the data collection methodology to everyone shortly. Since I am currently busy with a new subject, there might be a slight delay in organizing everything thoroughly. However, I will release a version for community use soon.

**Comment by Pter61** [comment]
The training code is now update.
